services:
  app:
    build: .
    container_name: posting_system
    ports:
      - "80:80" # This maps the host port http://localhost (80) to the container's port 80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true